package com.company;

import java.io.IOException;
import java.util.ArrayList;
import java.util.Collections;

public class Receipts {

    // Member ID of customer
    ArrayList<Member> members;

    public Receipts(ArrayList<Member> members) throws IOException {
        this.members = members;
    }

    // Returns all of the receipts of the transactions made by the member, along with the items, in a string
    public ArrayList<ArrayList<String>> getAllMemberReceipts() {
        ArrayList<ArrayList<String>> allReceipts = new ArrayList<>();

        // Retrieves all all of the receipts generated by member transactions
        for (Member currentMember : members) {
            ArrayList<ArrayList<String>> memberReceipts = currentMember.getAllReceiptsForCurrentMember();

            // Fills each member's receipt with the respective items, then adds the finished receipt to an ArrayList of all the receipts.
            for (ArrayList<String> receipt : memberReceipts) {
                ArrayList<String> receiptItems = new ArrayList<>();
                for (String receiptItem : receipt) {
                    receiptItems.add(receiptItem);
                }
                allReceipts.add(receiptItems);
            }
        }
        // Returns the ArrayList which stores all of the available member's receipts in one place.
        return allReceipts;
    }
}


